const Menu = [{
    id: 1,
    image: "images/poha.jpg",
    name: "Poha",
    category: "breakfast",
    price: "$4.00",
    description: "A light, flavorful dish made with flattened rice sautéed with onions, mustard seeds, and turmeric.",
    type:"Veg",
    },
    {
    id: 2,
    image: "images/omelette.jpg",
    name: "Omelette",
    category: "breakfast",
    price: "$7.00",
    description: "A classic omelette filled with your choice of cheese, vegetables, and herbs. Served with toast.",
    type:"Non-Veg",
    },
    {
    id: 3,
    image: "images/dosa.jpg",
    name: "Masala Dosa",
    category: "breakfast",
    price: "$8.00",
    description: "A crispy rice and lentil crepe filled with spiced mashed potatoes, served with coconut chutney and sambar.",
    type:"Veg",
    },
    {
    id: 4,
    image: "images/paratha.jpeg",
    name: "Paratha",
    category: "breakfast",
    price: "$5.50",
    description: "Flaky, layered flatbread made from whole wheat flour and can be either stuffed or plain served with yogurt and pickle on the side.",
    type:"Veg",
    },
    {
    id: 5,
    image: "images/upma.jpg",
    name: "Upma",
    category: "breakfast",
    price: "$4.50",
    description: "A savory dish made from semolina, sautéed with vegetables, spices, and garnished with fresh coriander.",
    type:"Veg",
    },
    {
    id: 6,
    image: "images/paneer.jpg",
    name: "Paneer Tikka Wrap",
    category: "lunch",
    price: "$9.00",
    description: "Grilled marinated paneer with bell peppers and onions, wrapped in a whole wheat tortilla with mint chutney.",
    type:"Veg",
    },
    {
    id: 7,
    image: "images/biryani.jpg",
    name: "Veg Biryani",
    category: "lunch",
    price: "$10.00",
    description: "Aromatic basmati rice cooked with mixed vegetables and spices, served with raita.",
    type:"Veg",
    },
    {
    id: 8,
    image: "images/aloo paratha.jpg",
    name: "Aloo Paratha",
    category: "lunch",
    price: "$8.00",
    description: "Flaky flatbread stuffed with spiced mashed potatoes, served with yogurt and pickles.",
    type:"Veg",
    },
    {
    id: 9,
    image: "images/cholee.jpeg",
    name: "Chole Bhature",
    category: "lunch",
    price: "$11.00",
    description: "Spicy chickpeas served with deep-fried bread, accompanied by onions and pickle.",
    type:"Veg",
    },
    {
    id: 10,
    image: "images/lunch.jpg",
    name: "Daily Lunch Special",
    category: "lunch",
    price: "$10.00",
    description: "Chef's choice of a special Indian dish available only for lunch, featuring fresh ingredients.",
    type:"Veg/Non-Veg",
    },
    {
    id: 11,
    image: "images/butter.jpg",
    name: "Butter Chicken",
    category: "dinner",
    price: "$16.00",
    description: "Tender chicken simmered in a rich and creamy tomato-based sauce, served with naan or rice.",
    type:"Non-Veg",
    },
    {
    id: 12,
    image: "images/paneer makhni.jpg",
    name: "Paneer Makhani",
    category: "dinner",
    price: "$15.00",
    description: "Soft paneer cubes cooked in a buttery tomato sauce, served with basmati rice or naan.",
    type:"Veg",
    },    
    {
    id: 13,
    image: "images/dal makhni.jpg",
    name: "Dal Makhani",
    category: "dinner",
    price: "$14.00",
    description: "Slow-cooked black lentils in a creamy sauce, served with rice or naan.",
    type:"Veg",
    },
    {
    id: 14,
    image: "images/tandoori.jpeg",
    name: "Tandoori Chicken",
    category: "dinner",
    price: "$16.00",
    description: "Marinated chicken cooked in a traditional tandoor, served with mint chutney and onion salad.",
    type:"Non-Veg",
    },
    {
    id: 15,
    image: "images/josh.jpg",
    name: " Rogan Josh",
    category: "dinner",
    price: "$18.00",
    description: "A flavorful lamb curry cooked with aromatic spices and yogurt, served with rice or naan.",
    type:"Non-Veg",
    },
    {
        id: 16,
        image: "images/gulab.jpg",
        name: "Gulab Jamun",
        category: "desserts",
        price: "$5.00",
        description: "Soft and syrup-soaked dough balls made from khoya, flavored with cardamom and rose water.",
        },
        {
        id: 17,
        image: "images/kheer.jpg",
        name: "Kheer",
        category: "desserts",
        price: "$5.50",
        description: "A traditional Indian rice pudding made with milk, sugar, and flavored with cardamom and nuts.",
        },
        {
        id: 18,
        image: "images/jalebi.jpg",
        name: "Jalebi",
        category: "desserts",
        price: "$4.00",
        description: "Crispy, spiral-shaped sweets soaked in sugar syrup, served hot or cold.",
        },    
        {
        id: 19,
        image: "images/rus.jpg",
        name: "Ras Malai",
        category: "desserts",
        price: "$6.00",
        description: "Soft cheese balls soaked in sweetened milk and flavored with cardamom and saffron.",
        },
        {
            id: 20,
            image: "images/tea.jpeg",
            name: "Tea",
            category: "drinks",
            price: "$3.00",
            description: "Spiced Indian tea brewed with milk and a blend of aromatic spices.",
            },
            {
            id: 21,
            image: "images/coffee.jpg",
            name: "Filter Coffee",
            category: "drinks",
            price: "$3.50",
            description: "South Indian-style coffee brewed with a blend of coffee and chicory, served with milk.",
            },
            {
            id: 22,
            image: "images/lassi.jpg",
            name: "Sweet Lassi",
            category: "drinks",
            price: "$4.00",
            description: "A refreshing yogurt drink sweetened with sugar and flavored with cardamom.",
            },    
];

export default Menu;